server:
  port: 8080
  servlet:
    context-path: /weather

spring:
  profiles:
    include:
       test
  application:
    name: weather

api:
  uri: https://api.openweathermap.org/data/2.5/forecast?q={location}&appid={apikey}&cnt={cnt}
  key: d2929e9483efc82c82c32ee7e02d563e